backendtest:
    image: sistearth/backend
    ports:
        - "443:8080"
        - "8787:8787"
    links:
        - databasetest

databasetest:
    image: sistearth/database-test
    environment:
        MYSQL_ROOT_PASSWORD: sistearth
        MYSQL_USER: sistearth
        MYSQL_PASSWORD: sistearth
        MYSQL_DATABASE: sistearth