backendtest:
    image: sistearth/backend
    ports:
        - "443:8080"
        - "8787:8787"
    links:
        - databasetest:database

databasetest:
    image: mongo

databaseimport:
    image: sistearth/import-data
    links:
        - databasetest:mongo